### ISSUE TITLE
Weird Underline Bug (?)

### ISSUE THREAD

**Issue by sampoder** [hackclub/v3#20] opened 2020-05-22 12:57 UTC
![captured](https://user-images.githubusercontent.com/39828164/82669550-3bb0ce80-9c6e-11ea-96d5-d3a923bc5372.gif)

Page: https://hackclub.com

Was trying to think off how we could design the new summer site, found this weird bug where whatever of "Online Clubs" or "Hackathons" is always highlighted no matter which of the two is being hovered over. (does that make sense?) the way to check it would be to go to the site and just play around hovering each of the links. I'm on MacOS with Chrome

**Comment by lachlanjc** [comment] 2020-05-29 14:16
Yep, I can reproduce this, only in Chrome though. Thanks for reporting. I've spent awhile investigating the cause or solution…I'm coming up short. If anyone else knows anything about what's happening here or could assist, that'd be great.

**Comment by mfarberbrodsky** [comment] 2020-06-01 10:26
I reproduced this in various places on https://hackclub.com/conduct/ as well - seems to be a general issue with links. I'll try to figure out what's going on.

**Comment by alchzh** [comment] 2020-09-11 21:52
I suggest simply not using `text-decoration-style: wavy`. It's completely broken on chromium without weird hacky outline tricks (that only work in some cases), and in any case, each browser makes them look completely different

**Comment by lachlanjc** [comment] 2020-09-11 22:04
Thanks for the link! Yeah, seems like it’s up to browsers to fix, so closing.

**Closed by lachlanjc** 2020-09-11 22:04 UTC
